config:
    shim:
        'numeral':
            exports:
                - 'numeral'

    paths:
        'numeral': 'bundles/pimlocalization/lib/numeral.js'
        'pim/locale-settings': 'bundles/pimlocalization/js/locale-settings.js'
        'pim/locale-settings/data': '../js/oro.locale_data.js'
        'pim/formatter/name': 'bundles/pimlocalization/js/formatter/name.js'
