config:
    shim:
        'numeral':
            exports:
                - 'numeral'
        'pim/formatter/number':
            deps:
                - 'numeral'
                - 'pim/locale-settings'

    paths:
        'numeral': 'bundles/pimlocalization/lib/numeral.js'
        'pim/locale-settings': 'bundles/pimlocalization/js/locale-settings.js'
        'pim/locale-settings/data': '../js/oro.locale_data.js'
        'pim/formatter/name': 'bundles/pimlocalization/js/formatter/name.js'
        'pim/formatter/address': 'bundles/pimlocalization/js/formatter/address.js'
        'pim/formatter/number': 'bundles/pimlocalization/js/formatter/number.js'
